name: 🐛 Bug Report
description: Create a bug report to help us improve
# labels: ["itype:bug", "stat:needs triage"]
labels: ["bug"]
body:

  - type: markdown
    attributes:
      value: "## Scala 3 Version"

  - type: input
    id: version
    attributes:
      label: Failing version
      placeholder: 3.x.y
      description: |
        Version or versions of Scala 3 in which the bug is found. [More info](https://github.com/nicolasstucki/issue-test/blob/main/issue-instructions.md#scala-3-version)
    validations:
      required: true

  - type: input
    id: last-good-version
    attributes:
      label: Last good version
      placeholder: 3.x.y / 2.x.y / None
      description: |
        Last good version if this bug is a regression. Leave empty if not known. [More info](https://github.com/nicolasstucki/issue-test/blob/main/issue-instructions.md#last-good-version)
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## Issue Reproduction"

  - type: dropdown
    id: issue-failure
    attributes:
      label: How does it fail?
      multiple: false
      # description: [More info](https://github.com/nicolasstucki/issue-test/blob/main/issue-instructions.md)
      options:
        - wrong run-time behavior
        - crashes at run-time
        - error at compile-time
        - crashes at compile-time
    validations:
      required: true

  - type: dropdown
    id: issue-reproducibility
    attributes:
      label: Level of reproducibility
      multiple: false
      # description: [More info](https://github.com/nicolasstucki/issue-test/blob/main/issue-instructions.md)
      options:
        - Reproducible with scalac/scala
        - Reproducible with scala-cli
        - Reproducible with scastie
        - Reproducible in external repo
        - Unreproducible
    validations:
      required: true

  - type: dropdown
    id: issue-minimization
    attributes:
      label: Level of minimization
      multiple: false
      # description: [More info](https://github.com/nicolasstucki/issue-test/blob/main/issue-instructions.md)
      options:
        - well minimized snippet
        - self-contained snippet
        - self-contained repo
        - repo with external dependencies
    validations:
      required: true

  - type: textarea
    id: bug-reproduction
    attributes:
      label: How to reproduce the bug
      description: |
        A clear and concise description of how to reproduce the bug. [More info and templates](https://github.com/nicolasstucki/issue-test/blob/main/issue-instructions.md#how-to-reproduce-the-bug)
      placeholder: Use templates in link above
    validations:
      required: true

  - type: checkboxes
    id: status
    attributes:
      label: Ease of reproduction
      description: Select all options that apply. [More info](https://github.com/nicolasstucki/issue-test/blob/main/issue-instructions.md#ease-of-reproduction)
      options:
        - label: Reproducible
          required: true
        - label: Reproducible without external dependencies
        - label: Reproducible with self-contained example
        - label: Reproducible with minimal example (can start fixing)


  - type: markdown
    attributes:
      value: "## Expectation"

  - type: textarea
    id: expectation
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen. [More info](https://github.com/nicolasstucki/issue-test/blob/main/issue-instructions.md#expected-behavior)
    validations:
      required: true


  - type: dropdown
    id: expectations
    attributes:
      label: It should
      multiple: true
      # description: [More info](https://github.com/nicolasstucki/issue-test/blob/main/issue-instructions.md)
      options:
        - compile
        - emit an error
        - emit a warning
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: Extra context or search terms
      description: |
        - Any other context about the problem
        - Search terms to help others discover this
    validations:
      required: false
