name: ðŸ› Bug Report
description: Create a bug report to help us improve
labels: ["itype:bug", "stat:needs triage"]
body:

  - type: input
    id: version
    attributes:
      label: Scala 3 version
      placeholder: 3.x.y
      description: |
        Version or versions of Scala 3 in which the bug is found. [More info](https://github.com/nicolasstucki/issue-test/blob/main/issue-instructions.md#scala-3-version)
    validations:
      required: true

  - type: input
    id: last-good-version
    attributes:
      label: Last good version
      placeholder: 3.x.y / None / Unknown
      description: Last good version if this bug is a regression. [More info](https://github.com/nicolasstucki/issue-test/blob/main/issue-instructions.md#last-good-version)
      value: Unknown
    validations:
      required: true

  - type: textarea
    id: bug-reproduction
    attributes:
      label: How to reproduce the bug
      description: |
        A clear and concise description of how to reproduce the bug. [More info and templates](https://github.com/nicolasstucki/issue-test/blob/main/issue-instructions.md#how-to-reproduce-the-bug)
      placeholder: |
        ```scala
        // Test.scala
        def test = xyz
        ```

        ```
        > scalac Test.scala
        | Error: ...
        | def test = xyz
        | //         ^^^ some error
        ```

    validations:
      required: true

  - type: textarea
    id: expectation
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen. [More info](https://github.com/nicolasstucki/issue-test/blob/main/issue-instructions.md#expected-behavior)
      placeholder: |
        - It should compile and produce code equivalent to ...
        - The generated code should run and produce ...
        - It should emit an error (or warning) at ... stating that ...
        - It should compile faster ...
    validations:
      required: true

  - type: checkboxes
    id: status
    attributes:
      label: Minimization
      description: Select all options that apply. [More info](https://github.com/nicolasstucki/issue-test/blob/main/issue-instructions.md#ease-of-reproduction)
      options:
        - label: Reproducible
          required: true
        - label: "Reproducible without external dependencies"
        - label: "Reproducible with self-contained example"
        - label: "Reproducible with minimal example (can start fixing)"

  - type: textarea
    id: extra
    attributes:
      label: Extra context or search terms
      description: |
        - Any other context about the problem
        - Search terms to help others discover this
    validations:
      required: false
