name: 🐛 Bug Report 2
description: Create a bug report to help us improve
body:

  - type: input
    id: version
    attributes:
      label: Fails in version
      placeholder: 3.x.y
      description: "Version of Scala 3. If you're not sure what version you're using, run `print scalaVersion` from sbt (if you're running scalac manually, use `scalac -version` instead)."
    validations:
      required: true

  - type: input
    id: last-good-version
    attributes:
      label: Last good version
      placeholder: 3.x.y / None
      value: None
    validations:
      required: false
   
  - type: checkboxes
    id: status
    attributes:
      label: Which operating systems have you used?
      description: You may select more than one.
      options:
        - label: Reproducible
          required: true
        - label: Reproducible without external dependencies 
        - label: Reproducible with minimal example
        - label: Identified source source of the issue
        - label: Identified solution
        - label: Implemented solution
        - label: Implemented solution

  
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: |
        Description ...

        Reproduction steps
        1. Go to ...
        2. Click on ...
        3. Scroll down to ...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expectation
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: What OS are you using?
      options:
        - macOS
        - Windows
        - Linux
        - Other (note only the above 3 are officially supported)

  - type: dropdown
    id: editor
    attributes:
      label: Editor/Extension
      options:
        - VS Code
        - Sublime
        - Nvim/Vim (coc-metals)
        - Nvim (nvim-metals)
        - Nvim/Vim (other)
        - Emacs (lsp-metals)
        - Emacs (other)
        - Other
        




  - type: textarea
    id: extra
    attributes:
      label: Extra context or search terms
      description: |
        - Any other context about the problem
        - Search terms to help others discover this
    validations:
      required: false
