name: 🐛 Bug Report 2
description: Create a bug report to help us improve
labels: ["itype:bug", "stat:needs triage"]
body:

  - type: input
    id: version
    attributes:
      label: Fails in version
      placeholder: 3.x.y
      description: "Version of Scala 3. If you're not sure what version you're using, run `print scalaVersion` from sbt (if you're running scalac manually, use `scalac -version` instead)."
    validations:
      required: true

  - type: input
    id: last-good-version
    attributes:
      label: Last good version
      placeholder: 3.x.y / None
      value: None
    validations:
      required: false
 
  - type: textarea
    id: what-happened
    attributes:
      label: Bug description
      description: A clear and concise description of how to reproduce the bug.
      value: |
        ##### Files
        <!-- Include full source with imports -->
        ```scala
        // Test.scala
        // TODO: add code
        ```
        
        <!-- SEPARATE COMPILATION: If a file must be compiled before the other, use the `_N` suffix for the file name. For example, if we have `Macro_1.sclala` and `Test_2.scala`, it means that we will first compile `Macro_1.sclala` and then compile `Test_2.scala` with a dependency on `Test_2.scala`. `Macro.sclala` and `Test.scala` means that we compile both at the same time (for macros avoid this one unless it is the only way to reproduce the issue). -->
        <!-- BACKWARDS COMPAT: If a dependency must be compiled with an older version of the compiler, use the `_c3.x.y` suffix to indicate the older version (in combination with `_N`) -->
        
        #####  Reproduction
        ```
        > scalac Test.scala
        ```

        ##### Output

        ```
        // TODO
        ```

        <!-- IF THE OUTPUT CONTAINS A STACK TRACE IS TOO LONG -->
        <!--
        <details>
        <summary>Detailed Output</summary>

        ```scala
        // TODO add output here
        ```
        </details>
        -->
                
    validations:
      required: true

  - type: textarea
    id: expectation
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
   
  - type: checkboxes
    id: status
    attributes:
      label: "Status"
      description: "Select all options that apply"
      options:
        - label: Reproducible
          required: true
        - label: "Reproducible without external dependencies"
        - label: "Reproducible with minimal example"
        - label: "Identified source source of the issue"
        - label: "Identified solution"
        - label: "Implemented solution"

  - type: textarea
    id: extra
    attributes:
      label: Extra context or search terms
      description: |
        - Any other context about the problem
        - Search terms to help others discover this
    validations:
      required: false
